# Generated by Django 5.1.4 on 2025-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
